[package]
name = "yrba"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.3", features = ["tracing", "log", "default"] }
env_logger = "0.11.8"
flate2 = "1.1.1"
log = "0.4.27"
ssh2 = "0.9.5"
tar = "0.4.44"
toml = "0.8.22"
